### ISSUE TITLE
CONTRIBUTING link seems broken

### ISSUE THREAD

**Issue by tikkss** [apache/arrow-flight-sql-postgresql#132]
Looks like the CONTRIBUTING.md link in README.md seems broken.

https://github.com/apache/arrow-flight-sql-postgresql/blob/0493e334ce1b3242319f3b906fafe8f9243e736d/README.md?plain=1#L29

**Comment by kou** [comment]
Good catch!
Do you want to open a pull request that fixes this?

**Comment by tikkss** [comment]
Sure!
