### ISSUE TITLE
Edit on GitHub seems broken

### ISSUE THREAD

**Issue by tikkss** [apache/arrow-flight-sql-postgresql#134]
Looks like the `Edit on GitHub` link in https://arrow.apache.org/flight-sql-postgresql seems broken.

![image](https://github.com/apache/arrow-flight-sql-postgresql/assets/4122070/47ca4afe-5cc3-41b8-ba4d-dfa13fab3884)

**Comment by kou** [comment]
Good catch!
We have a typo...:
https://github.com/apache/arrow-flight-sql-postgresql/blob/e529f3930851b48a1961bdc3f7d8d459793637ba/doc/source/conf.py#L104

**Comment by tikkss** [comment]
Thanks! [devel website](https://arrow.apache.org/flight-sql-postgresql/devel) is corrected.
