### ISSUE TITLE
The back quote seems missed

### ISSUE THREAD

**Issue by tikkss** [apache/arrow-flight-sql-postgresql#143]
Looks like the back quote in [Install source documentation](https://arrow.apache.org/flight-sql-postgresql/current/install.html#source) seems missed.

https://github.com/apache/arrow-flight-sql-postgresql/blob/d2ee5170ebbd9f0e664c02c9464d3ab2e98a573b/doc/source/install.md?plain=1#L70

**Comment by kou** [comment]
Good catch!
Could you open a PR that fixes the typo?

**Comment by tikkss** [comment]
Sure!
