### ISSUE TITLE
`--output-document` of `wget` seems missed in install doc

### ISSUE THREAD

**Issue by tikkss** [apache/arrow-flight-sql-postgresql#145]
Looks like the `--output-document` of `wget` seems missed in [Install source documentation](https://arrow.apache.org/flight-sql-postgresql/devel/install.html#source). `wget` saved as `closer.lua?action=download&filename=arrow%2Fapache-arrow-flight-sql-postgresql-0.1.0%2Fapache-arrow-flight-sql-postgresql-0.1.0.tar.gz` without `--output-document`. Unable to extract because the file name is different.

https://github.com/apache/arrow-flight-sql-postgresql/blob/d2ee5170ebbd9f0e664c02c9464d3ab2e98a573b/doc/source/install.md?plain=1#L80-L81

Maybe, add to `--output-document` (`-O`) will fix it.

```diff
-wget "https://www.apache.org/dyn/closer.lua?action=download&filename=arrow/apache-arrow-flight-sql-postgresql-${version}/apache-arrow-flight-sql-postgresql-${version}.tar.gz"
+wget "https://www.apache.org/dyn/closer.lua?action=download&filename=arrow/apache-arrow-flight-sql-postgresql-${version}/apache-arrow-flight-sql-postgresql-${version}.tar.gz" -O apache-arrow-flight-sql-postgresql-${version}.tar.gz
```

**Comment by kou** [comment]
Ah, you're right.
Could you open a PR for this?

**Comment by kou** [comment]
Could you use `--output-file=apache-...` instead of `-O arrow-...`?
I want to use long option style as much as possible because it's more self descriptive.

**Comment by tikkss** [comment]
Sure!

Thanks for your polite explanation. I would like to use long option style.
