### ISSUE TITLE
IOError: Invalid: SCRAM auth method isn't supported yet

### ISSUE THREAD

**Issue by tumluliu** [apache/arrow-flight-sql-postgresql#187]
Hi, thank you for making this very nice library. I'm trying it by following the [official doc]() but could not even make the "How to connect" successful. It complained with:

```
IOError: Invalid: SCRAM auth method isn't supported yet. Detail: Unauthenticated. Detail: Unauthenticated
```

at this line I believe:

```c++
ARROW_ASSIGN_OR_RAISE(auto bearer_token, client->AuthenticateBasicToken(call_options, user, password));
```

From the postgresql server side, I saw such a log entry accordingly:

```
2024-05-15 15:38:25.605 UTC [263] LOG:  background worker "arrow-flight-sql: executor: 16118212404317981807" (PID 28668) exited with exit code 1
```

And I can confirm the provided `user` and `password` are correct. Could you please provide me some hints that where the problem could be? Thanks a lot!

**Comment by tumluliu** [comment]
ok, I found the reason. It's not yet implemented according to [here](https://github.com/apache/arrow-flight-sql-postgresql/blob/6e013be8491305295c76632b32f21b84296e5bb0/src/afs.cc#L1750). Will adjust my pg_hba accordingly, and close this issue

**Comment by kou** [comment]
Right.
Challenge-response style auths aren't implemented yet.
